// -*-c++-*-
// Generated by GenerateIconFontCppHeaders.py for language C++11
// IconFontCppHeaders by Juliette Foucaut https://github.com/juliettef/IconFontCppHeaders
// distributed under the zlib license.
//
// Fontawesome font from website: fontawesome.io
// Created by Dave Gandy and distributed under the SIL Open Font License 1.1
// from https://raw.githubusercontent.com/FortAwesome/Font-Awesome/master/src/icons.yml
// for use with https://github.com/FortAwesome/Font-Awesome/blob/master/fonts/fontawesome-webfont.ttf
// Modified by AOR to include some new glyphs

#pragma once

#define ICON_SM_ARROWS "!"
#define ICON_SM_MOUSE_POINTER "\""
#define ICON_SM_COMPASS_ANGLE "#"
#define ICON_SM_RULER "$"
#define ICON_SM_PENCIL "%"
#define ICON_SM_ALIGNMENT "&"
#define ICON_SM_COG "'"
#define ICON_SM_TAG "("
#define ICON_SM_FLOPPY_O ")"
#define ICON_SM_QUESTION "*"
#define ICON_SM_TIMES "+"
#define ICON_SM_VBAR ","
