// Public interface for src/gui_interface.f90

//xx// Variables made available through host association in 
//xx// gui_interface.f90. See gui_interface.f90 for documentation.
// Sticks
extern "C" struct c_stick {
  float r1[3];
  float r2[3];
  float rmid[3];
  float length;
  float thick;
  float rgb[3];
  float rot[4][4];
};

// Atoms
extern "C" struct c_atom {
  char name[11];
  int z;
  float r[3];
  float rad;
  float rgb[3];
};
extern "C" int nat;
extern "C" struct c_atom *at;

// Bonds
extern "C" struct c_bond {
  int i1;
  int i2;
  struct c_stick s;
};
extern "C" int nbond;
extern "C" struct c_bond *bond;

// Critical points
extern "C" struct c_critp {
  float r[3];
  int type;
  float rgb[3];
  char name[11];
};
extern "C" int ncritp;
extern "C" struct c_critp *critp;

// Unit cell
extern "C" bool usecell;
extern "C" float cell_x0[3];
extern "C" float cell_lat[3][3];

// Bounding box
extern "C" float box_xmin[3];
extern "C" float box_xmax[3];
extern "C" float box_xcm[3];
extern "C" float box_xmaxlen;

//xx// Procedures made available in gui_interface.f90

// Initialize critic2
extern "C" void critic2_initialize();

// End the critic2 run
extern "C" void critic2_end();

// Read a new molecule/crystal from an external file
extern "C" void call_structure(const char **filename, int isMolecule); 

// Calculate critical points for the current field
extern "C" void call_auto(); 

extern "C" void get_num_atoms(int *n);
extern "C" void get_atom_position(int n, int *atomicN, double *x, double *y, double *z);
extern "C" void num_of_bonds(int n, int *nstarN);
extern "C" void get_atom_bond(int n_atom, int nstarIdx, int *connected_atom, bool *neighCrystal );
extern "C" void num_of_crit_points(int *n_critp);
extern "C" void get_cp_pos_type(int cpIdx, int *type, double *x, double *y, double *z); //get critical points from critic2 after thay have bean generated by auto_cp

